feat(sfdx-project): add name property to project schema
forcedotcom/schemas pull request #35
Opened 2021-04-01 21:15 UTC by cafreeman

### What does this PR do?

Adds a name property to the `sfdx-project.json` schema

### What issues does this PR fix or reference?

https://gus.lightning.force.com/one/one.app#/alohaRedirect/a07AH0000009lOcYAI

### Functionality Before

### Functionality After

Should be no different except that the name field is documented.

2021-04-02 19:32 UTC, amphro requested changes

2021-04-02 19:32 UTC, amphro commented on sfdx-project.schema.json
> +      "description": "The name of your SFDX project."
Change this to "Salesforce project."

2021-04-05 19:35 UTC, cafreeman commented on sfdx-project.schema.json
> +      "description": "The name of your SFDX project."
👍 changed

2021-04-05 19:51 UTC, lcampos commented
@cafreeman I think this is ok, are you also going to update the documentation around this file ? e.g. https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm, https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev2gp_config_file.htm

We should also open a PR to add this new attribute to the current scaffold commands and include this new attribute (https://github.com/forcedotcom/salesforcedx-templates).

cc @ntotten @smaddox-sf

2021-04-05 20:11 UTC, cafreeman commented
@lcampos 👋 I've actually already opened up a PR over on the templates repo if you'd like to take a look https://github.com/forcedotcom/salesforcedx-templates/pull/296

2021-04-05 21:29 UTC, xyc approved these changes

2021-04-05 21:50 UTC, lcampos approved these changes

2021-04-06 04:18 UTC, amphro approved these changes

2021-04-06 15:09 UTC, merged